name: passbook_app
description: Passbook Finance App Fixed
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  path_provider: ^2.1.2

flutter:
  uses-material-design: true
