name: fintech_app
description: Premium Fintech App
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0

flutter:
  uses-material-design: true
