name: Flutter APK Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Clean project
        run: rm -rf android ios build

      - name: Recreate Flutter project (CRITICAL FIX)
        run: flutter create .

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: fintech-apk
          path: build/app/outputs/flutter-apk/app-release.apk
